### ISSUE TITLE
Bug report minor changes

### ISSUE THREAD

**Issue by brandon-005** [Saikou-Bot/SaikouBotV2#104]
- [x] Send message in channel informing user that they have been DM’ed by the bot. 
- [x] Catch error if user has DM’s disabled

**Comment by ha6000** [comment]
I think I already catch on error, but I can always double check

**Comment by brandon-005** [comment]
Yeah I wasn't 100% sure if it was already done so I just put it there just incase

**Comment by ha6000** [comment]
oh wait, it reverts to the current channel if it cant dm
