### ISSUE TITLE
Redo items/shop system

### ISSUE THREAD

**Issue by brandon-005** [Saikou-Bot/SaikouBotV2#27]
each item will be in a folder called items, each item will have a file where other information can be found about it such as: emoji, price and functionality. When a user tries to use an item, the item files will be referred to. 

- [x] handler to load item files, with category folders for each pages items
- [x] Add item command, will add the itemName and if its’s in shop to MongoDB (Boolean, true false) commandExample: .additem ItemName true <= would be in shop because it’s true. 
- [x] Remove item from shop command (sets item Boolean to false)
- [x] Delete item command, will delete the item from MongoDB.

Item files: 
- [x] Shop command listing all the item files, listing info such as price etc. 

Commands: 
- [x] Buy command to purchase items.
- [x] Inventory displaying items the user owns.
- [x] Sell command.

**Comment by ha6000** [comment]
It would be nice, but if we are gone have items with unique abilities we have to code it would be much better to have it like commands where each item has its own file with its properties and functons
