### ISSUE TITLE
Finish suggest command

### ISSUE THREAD

**Issue by brandon-005** [Saikou-Bot/SaikouBotV2#41]
Finalise the suggest command to add more features.

- [x] Suggestion numbers which will increase as each suggestion is posted.
- [x] Delete all messages that aren’t the suggest command
- [x] If more than 15 suggestions, move to feature channel.
- [x] Delete .suggest user command.
- [x] Able to delete your own suggestion?

**Comment by ha6000** [comment]
> If more than 15 suggestions, add to a trello card.

by that do you mean, 15 votes?

**Comment by ha6000** [comment]
and should down votes decrease the number?

**Comment by brandon-005** [comment]
15+ up reactions, we could have it be reduced it they did a down reaction yes

**Comment by ha6000** [comment]
> Able to delete your own suggestion?

by down voting your own suggestion?

**Comment by brandon-005** [comment]
Sure, or maybe have them add a certain reaction to delete it

**Comment by ha6000** [comment]
but then we need to give people perms to add reactions

**Comment by brandon-005** [comment]
Ah that’s true, I think down voting would be the best option then
