### ISSUE TITLE
Tank, AA, Helicopter command

### ISSUE THREAD

**Issue by brandon-005** [Saikou-Bot/SaikouBotV2#46]
Based off the last versions TAH command, similar to rock paper scissors. Will award users with money if it's correct, and deduct money if wrong.

- [x] Custom emojis
- [x] Draws, wins, loses
- [x] Award the user money if they win
- [x] Multiplayer Option 
- [x] AI Option
- [x] Award user currency if they win and deduct if they lose
- [x] Send multiplayer reaction to DMs so users can’t cheat.
- [x] Permission checking If user is bot or yourself

**Comment by ha6000** [comment]
rock paper scissors against real people and then if you provide ai as the player it will use ai
